### ISSUE TITLE
Whitelist weapons so they don't count as a team kill

### ISSUE THREAD

**Issue by stajs** [stajs/Stajs.Procon.TeamKillTracker#33]
[Tomgun](https://forum.myrcon.com/showthread.php?8690-Team-Kill-Tracker-%283-5-0%29-12-Dec-2014&p=113732&viewfull=1#post113732):

> could there be an option to have certain weapons unpunlishable (in a whitelist), reason is I know claymores are a looked upon as stupid in hardcore but in my opinion if you just run around like a chicken and dont open your eyes then its your fault for running into an team mates claymore (go play softcore). The thing has a glowing icon and the amount of times I have layed a claymore to protect my back, someone just spawns on me and runs off right into it when it clear as day is countless. Then they punish you because they are blind!!!

**Comment by Zillion01** [comment]
Add in line 781

`if (kill.Weapon == "U_Medkit" || kill.Weapon == "U_Claymore" || kill.Weapon == "U_Claymore_Recon" || kill.Weapon == "U_M15" || kill.Weapon == "U_SLAM")
			    return;`

**Comment by stajs** [comment]
Thanks for the suggestion, but I no longer have access to a server to test things on so unfortunately I'm going to archive this repo.
